name: "Versions"
author: "Matt Wynne"
description: "Read version numbers from git tags and CHANGELOG to see if a release is needed"

inputs:
  github-token:
    description: "Github token to use when calling GitHub API to create Release"
    default: ""

outputs:
  version:
    description: "Version number"

runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.github-token }}
